"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, FileText, Loader2, Plus, Save, Send, TriangleAlert } from "lucide-react";
import { useAuth } from "@/lib/auth-provider";
import { apiFetch, getApiErrorMessage } from "@/lib/api/client-fetch";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Article = { id: string; slug: string; title: string; description: string; content: string; category?: string; image?: string; status: "draft" | "published" | "archived"; updatedAt?: string; readingMinutes?: number };
type FormState = { id?: string; title: string; image: string; category: string; summary: string; content: string };
const emptyForm: FormState = { title: "", image: "", category: "", summary: "", content: "" };
function words(value: string) { return value.trim().match(/\S+/g)?.length ?? 0; }

export default function ArticlesPage() {
  const { user, loading: authLoading } = useAuth();
  const allowed = user?.role === "super_admin" && user?.tenantId === "platform";
  const [articles, setArticles] = useState<Article[]>([]); const [form, setForm] = useState<FormState>(emptyForm);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const guidance = useMemo(() => { const messages: string[] = []; if (form.summary.trim().length < 80) messages.push("Résumé trop court : ajoutez une phrase."); if (!form.image.trim()) messages.push("Ajoutez une image pour améliorer le partage."); if (form.content.trim().length < 500) messages.push("Article encore court : développez une idée ou ajoutez un exemple."); if (form.title.length > 70) messages.push("Titre un peu long : essayez de le raccourcir."); return messages; }, [form]);
  const load = useCallback(async () => { if (!allowed) return; setLoading(true); try { const data = await apiFetch<{ articles: Article[] }>("/api/platform/articles"); setArticles(data.articles); } catch (e) { setError(getApiErrorMessage(e, "Impossible de charger les articles.")); } finally { setLoading(false); } }, [allowed]);
  useEffect(() => { if (!authLoading) void load(); }, [authLoading, load]);
  function edit(article: Article) { setForm({ id: article.id, title: article.title, image: article.image ?? "", category: article.category ?? "", summary: article.description, content: article.content }); setNotice(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function save(action: "draft" | "publish") { setError(""); setNotice(""); setSaving(true); try { const endpoint = form.id ? `/api/platform/articles/${form.id}` : "/api/platform/articles"; const result = await apiFetch<{ id: string; slug: string; status: string }>(endpoint, { method: form.id ? "PATCH" : "POST", body: { ...form, action } }); setForm((current) => ({ ...current, id: result.id })); setNotice(action === "publish" ? "Article publié. Il est maintenant visible sur le blog." : "Brouillon enregistré. Vous pourrez le reprendre plus tard."); await load(); } catch (e) { setError(getApiErrorMessage(e, "Impossible d’enregistrer l’article.")); } finally { setSaving(false); } }
  if (authLoading) return <main className="grid min-h-screen place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></main>;
  if (!allowed) return <main className="mx-auto max-w-2xl p-8"><Card><CardHeader><CardTitle>Accès réservé</CardTitle></CardHeader><CardContent><p className="text-muted-foreground">La publication est réservée à l’administrateur de la plateforme.</p><Button asChild variant="outline" className="mt-5"><Link href="/platform">Retour à la plateforme</Link></Button></CardContent></Card></main>;
  return <main className="min-h-screen bg-muted/25 py-8"><div className="mx-auto max-w-7xl space-y-6 px-4 sm:px-6">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><Button asChild variant="ghost" size="sm" className="-ml-3 mb-2"><Link href="/platform"><ArrowLeft />Retour à la plateforme</Link></Button><h1 className="text-3xl font-black tracking-tight">Articles</h1><p className="mt-1 text-muted-foreground">Écrivez simplement. Sentrys prépare automatiquement l’article pour le web.</p></div><Button variant="outline" onClick={() => { setForm(emptyForm); setNotice(""); }}><Plus />Nouvel article</Button></header>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><Card><CardContent className="space-y-5 pt-6">
      <div className="space-y-2"><Label htmlFor="title">Titre de l’article</Label><Input id="title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Ex. Comment mieux préparer les prises de poste" /></div>
      <div className="space-y-2"><Label htmlFor="image">Image de couverture</Label><Input id="image" value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} placeholder="Collez l’adresse d’une image" /><p className="text-xs text-muted-foreground">L’import direct d’images pourra être ajouté ensuite ; une adresse d’image suffit aujourd’hui.</p></div>
      <div className="space-y-2"><Label htmlFor="category">Catégorie</Label><Input id="category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Conseils, réglementation, produit…" /></div>
      <div className="space-y-2"><div className="flex justify-between"><Label htmlFor="summary">Résumé court</Label><span className="text-xs text-muted-foreground">{form.summary.length} caractères</span></div><Textarea id="summary" rows={3} value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="En deux phrases, qu’est-ce que le lecteur va apprendre ?" /></div>
      <div className="space-y-2"><div className="flex justify-between"><Label htmlFor="content">Contenu</Label><span className="text-xs text-muted-foreground">Environ {Math.max(1, Math.ceil(words(form.content) / 220))} min de lecture</span></div><Textarea id="content" rows={20} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder={"Rédigez votre article ici.\n\nUtilisez ## pour un grand intertitre et ### pour un sous-titre."} className="font-mono leading-relaxed" /></div>
      {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{notice && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</div>}
      <div className="flex flex-wrap justify-end gap-3 border-t pt-5"><Button variant="outline" disabled={saving} onClick={() => void save("draft")}>{saving ? <Loader2 className="animate-spin" /> : <Save />}Enregistrer le brouillon</Button><Button disabled={saving} onClick={() => void save("publish")}>{saving ? <Loader2 className="animate-spin" /> : <Send />}Publier</Button></div>
    </CardContent></Card><aside className="space-y-6"><Card><CardHeader><CardTitle className="text-lg">Assistant de publication</CardTitle></CardHeader><CardContent className="space-y-3">{guidance.length === 0 ? <div className="flex gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0" />Votre article est prêt à être publié.</div> : guidance.map((message) => <div key={message} className="flex gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><TriangleAlert className="mt-0.5 h-5 w-5 shrink-0" />{message}</div>)}<p className="pt-2 text-xs leading-relaxed text-muted-foreground">L’adresse, l’aperçu de partage, le texte de l’image, le sommaire et le référencement sont générés automatiquement.</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-lg">Vos articles</CardTitle></CardHeader><CardContent className="space-y-2">{loading ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="animate-spin" />Chargement…</div> : articles.length === 0 ? <p className="text-sm text-muted-foreground">Aucun article créé dans le CRM.</p> : articles.map((article) => <button key={article.id} onClick={() => edit(article)} className="w-full rounded-xl border p-3 text-left transition hover:bg-muted"><div className="flex items-start justify-between gap-2"><span className="line-clamp-2 text-sm font-semibold">{article.title}</span>{article.status === "published" ? <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" /> : <FileText className="h-4 w-4 shrink-0 text-amber-600" />}</div><div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="h-3 w-3" />{article.readingMinutes ?? 1} min · {article.status === "published" ? "Publié" : "Brouillon"}</div></button>)}{form.id && articles.find((a) => a.id === form.id)?.status === "published" && <Button asChild variant="outline" className="mt-3 w-full"><Link href={`/blog/${articles.find((a) => a.id === form.id)?.slug}`} target="_blank">Voir l’article<ExternalLink /></Link></Button>}</CardContent></Card>
    </aside></div>
  </div></main>;
}