import { appLogger } from "@/lib/observability/logger";
import { NextRequest, NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { forbidden, isSuperAdmin, requireTenantUser } from "@/app/api/_utils/withTenant";
import { adminDb } from "@/lib/firebase/admin";
export const runtime = "nodejs";
function json(status: number, body: unknown) { const response = NextResponse.json(body, { status }); response.headers.set("Cache-Control", "no-store"); return response; }
function iso(value: unknown) { if (value && typeof value === "object" && "toDate" in value) return (value as { toDate(): Date }).toDate().toISOString(); return null; }
async function authorize(req: NextRequest) { const auth = await requireTenantUser(req); if (!auth.ok) return auth; if (!isSuperAdmin(auth.role) || auth.tenantId !== "platform") return { ok: false as const, res: forbidden("Super administrateur plateforme requis") }; return auth; }
export async function GET(req: NextRequest) { const auth = await authorize(req); if (!auth.ok) return auth.res; try { const snapshot = await adminDb.collection("contactRequests").orderBy("createdAt", "desc").limit(100).get(); const items = snapshot.docs.map((doc) => { const data = doc.data(); return { id: doc.id, name: String(data.name ?? ""), email: String(data.email ?? ""), company: data.company ? String(data.company) : null, reason: String(data.reason ?? ""), message: String(data.message ?? ""), status: String(data.status ?? "new"), createdAtIso: iso(data.createdAt) }; }); return json(200, { ok: true, items }); } catch (error) { appLogger.error("platform.contact_requests.load_failed", error, { actorUid: auth.uid }); return json(500, { ok: false, error: "Impossible de charger les demandes." }); } }
export async function PATCH(req: NextRequest) { const auth = await authorize(req); if (!auth.ok) return auth.res; try { const body = await req.json().catch(() => null) as { id?: unknown; status?: unknown } | null; const id = String(body?.id ?? "").trim(); const status = String(body?.status ?? "").trim(); if (!id || !["new", "processed"].includes(status)) return json(400, { ok: false, error: "Demande ou statut invalide." }); const ref = adminDb.collection("contactRequests").doc(id); const snapshot = await ref.get(); if (!snapshot.exists) return json(404, { ok: false, error: "Demande introuvable." }); await ref.update({ status, updatedAt: FieldValue.serverTimestamp(), processedAt: status === "processed" ? FieldValue.serverTimestamp() : null, processedBy: status === "processed" ? auth.uid : null }); return json(200, { ok: true }); } catch (error) { appLogger.error("platform.contact_requests.update_failed", error, { actorUid: auth.uid }); return json(500, { ok: false, error: "Impossible de mettre à jour la demande." }); } }