"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Loader2, Mail, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiFetch, getApiErrorMessage } from "@/lib/api/client-fetch";
import { useAuth } from "@/lib/auth-provider";
type RequestItem = { id: string; name: string; email: string; company: string | null; reason: string; message: string; status: string; createdAtIso: string | null };
const labels: Record<string, string> = { demo: "Démonstration", tarifs: "Tarifs", support: "Assistance", partenariat: "Partenariat" };
export default function PlatformContactsPage() { const { user, loading: authLoading } = useAuth(); const allowed = user?.role === "super_admin" && user?.tenantId === "platform"; const [items, setItems] = useState<RequestItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!allowed) return; setLoading(true); setError(""); try { const data = await apiFetch<{ items: RequestItem[] }>("/api/platform/contact-requests"); setItems(data.items); } catch (reason) { setError(getApiErrorMessage(reason)); } finally { setLoading(false); } }, [allowed]);
  useEffect(() => { if (!authLoading) void load(); }, [authLoading, load]);
  async function process(id: string) { try { await apiFetch("/api/platform/contact-requests", { method: "PATCH", body: { id, status: "processed" } }); await load(); } catch (reason) { setError(getApiErrorMessage(reason)); } }
  if (authLoading) return <main className="grid min-h-screen place-items-center"><Loader2 className="animate-spin" /></main>; if (!allowed) return <main className="p-8">Accès réservé.</main>;
  return <main className="min-h-screen bg-muted/25 py-8"><div className="mx-auto max-w-6xl space-y-6 px-4"><header className="flex flex-wrap items-center justify-between gap-4"><div><Button asChild variant="ghost" className="-ml-3"><Link href="/platform"><ArrowLeft />Plateforme</Link></Button><h1 className="mt-2 text-3xl font-black">Demandes reçues</h1><p className="text-muted-foreground">Prospects et demandes d’assistance envoyés depuis le site.</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw />Actualiser</Button></header>{error && <p className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{loading ? <div className="flex items-center gap-2 text-muted-foreground"><Loader2 className="animate-spin" />Chargement…</div> : items.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">Aucune demande reçue.</CardContent></Card> : <div className="grid gap-4">{items.map((item) => <Card key={item.id} className={item.status === "new" ? "border-primary/30" : "opacity-75"}><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{item.name}{item.company ? ` — ${item.company}` : ""}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{item.createdAtIso ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAtIso)) : "Date indisponible"}</p></div><Badge variant={item.status === "new" ? "default" : "outline"}>{item.status === "new" ? "À traiter" : "Traitée"}</Badge></div></CardHeader><CardContent><p className="whitespace-pre-wrap leading-relaxed">{item.message}</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild variant="outline"><a href={`mailto:${item.email}?subject=Sentrys — ${encodeURIComponent(labels[item.reason] ?? item.reason)}`}><Mail />Répondre à {item.email}</a></Button>{item.status === "new" && <Button onClick={() => void process(item.id)}><CheckCircle2 />Marquer comme traitée</Button>}<Badge variant="secondary">{labels[item.reason] ?? item.reason}</Badge></div></CardContent></Card>)}</div>}</div></main>;
}